# Change these first
owner: LxnChan # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Baidu（百度）
    url: https://www.baidu.com
  - name: Official（泠泫凝的异次元空间-主页）
    url: https://lxnchan.cn
  - name: 115Wiki
    url: https://115.anavi.cn
  - name: EnderChest（末影箱-云盘）
    url: https://enderchest.anavi.cn
  - name: Gravtar代理
    url: https://gravatar.arlxn.top
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.lxnchan.cn
  # baseUrl: /your-repo-name
  logoUrl: https://gh-proxy.arlxn.top/https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: 泠泫凝 的服务状态
  introTitle: "此处展现的服务状态仅供参考。"
  introMessage: 如有问题请发邮件至admin@arlxn.top
  navbar:
    - title: 服务状态
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
